specVersion: 0.2.0
name: turing-staging-subql
version: 0.0.4
description: Any queries for subquery for OAK's Turing Staging network
repository: https://github.com/subquery/oak-subql
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://rpc.turing-staging.oak.tech'
  genesisHash: '0xd54f0988402deb4548538626ce37e4a318441ea0529ca369400ebec4e04dfe4b'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/imstar15/turing-staging-subql
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers: 
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler