{
 "title": "Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Failed Task Scheduling",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNotifyTask\" },\n    success: { equalTo: false }\n  }) {\n    nodes {\n      timestamp blockHeight method args\n    }\n  }\n}",
     "timePath": "timestamp"
    },
    {
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNativeTransferTask\" },\n    success: { equalTo: false }\n  }) {\n    nodes {\n      timestamp blockHeight method args\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Failed Task Scheduling",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "aliasBy": "Native Transfer",
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNativeTransferTask\" },\n    success: { equalTo: false }\n  }) {\n    nodes {\n      timestamp method\n    }\n  }\n}",
     "timePath": "timestamp"
    },
    {
     "aliasBy": "Notify",
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNotifyTask\" },\n    success: { equalTo: false }\n  }) {\n    nodes {\n      timestamp method\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Successful Task Scheduling",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNotifyTask\" },\n    success: { equalTo: true }\n  }) {\n    nodes {\n      timestamp blockHeight method args\n    }\n  }\n}",
     "timePath": "timestamp"
    },
    {
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNativeTransferTask\" },\n    success: { equalTo: true }\n  }) {\n    nodes {\n      timestamp blockHeight method args\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Successful Task Scheduling",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "aliasBy": "Native Transfer",
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNativeTransferTask\" },\n    success: { equalTo: true }\n  }) {\n    nodes {\n      timestamp method\n    }\n  }\n}",
     "timePath": "timestamp"
    },
    {
     "aliasBy": "Notify",
     "constant": 6.5,
     "dataPath": "extrinsics.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  extrinsics(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"scheduleNotifyTask\" },\n    success: { equalTo: true }\n  }) {\n    nodes {\n      timestamp method\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Successful Task Execution",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "events.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  events(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"Notify\" }\n  }) {\n    nodes {\n      timestamp blockHeight method data\n    }\n  }\n}",
     "timePath": "timestamp"
    },
    {
     "constant": 6.5,
     "dataPath": "events.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  events(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"SuccesfullyTransferredFunds\" }\n  }) {\n    nodes {\n      timestamp blockHeight method data\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Successful Task Execution",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "aliasBy": "SuccesfullyTransferredFunds",
     "constant": 6.5,
     "dataPath": "events.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  events(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"SuccesfullyTransferredFunds\" }\n  }) {\n    nodes {\n      timestamp method\n    }\n  }\n}",
     "timePath": "timestamp"
    },
    {
     "aliasBy": "Notify",
     "constant": 6.5,
     "dataPath": "events.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  events(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" },\n    method: { equalTo: \"Notify\" }\n  }) {\n    nodes {\n      timestamp method\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Transfers (Is this all transactions?)",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "transfers.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  transfers(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" }\n  }) {\n    nodes {\n      timestamp blockNumber toAccountId fromAccountId balanceChange\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "aliasBy": "Unique Wallets (All Time)",
     "constant": 6.5,
     "dataPath": "accounts.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  accounts {\n    nodes {\n      id\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Global Events Table",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "events.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  events(filter: { timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\", lessThanOrEqualTo: \"${__to:date:iso}\" }}) {\n    nodes {\n      timestamp\n      blockHeight\n      method\n      module\n      data\n      extrinsic {\n        success\n        args\n      }\n    }\n  }\n}",
     "timePath": "timestamp"
    }
   ]
  }
 ]
}